[package]
name = "grolang"
version = "0.0.1"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
assert_approx_eq = "1.1.0"
strum = "0.26"
strum_macros = "0.26"
once_cell = "1.19.0"
pest = "2.7.10"
pest_derive = "2.7.10"
lazy_static = "1.5.0"

