[package]
name = "grolang"
version = "0.0.1"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
assert_approx_eq = "1.1.0"

